export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1d1b1d',
        'surface-tint': '#665971',
        'on-tertiary-fixed-variant': '#40493c',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#d1c0dd',
        'secondary-container': '#dcdddd',
        'tertiary-fixed-dim': '#c0cab8',
        'surface-bright': '#fdf8fa',
        'on-secondary-fixed': '#1a1c1c',
        background: '#fdf8fa',
        'secondary-fixed-dim': '#c6c6c7',
        'surface-dim': '#ded9db',
        'on-secondary': '#ffffff',
        'block-pink': '#EFD4D4',
        'surface-variant': '#e6e1e3',
        'on-error': '#ffffff',
        primary: '#000000',
        'secondary-fixed': '#e2e2e2',
        surface: '#fdf8fa',
        'on-primary-fixed-variant': '#4e4259',
        error: '#ba1a1a',
        'on-surface-variant': '#4a454c',
        'surface-container-lowest': '#ffffff',
        secondary: '#5d5f5f',
        'tertiary-fixed': '#dce6d3',
        'primary-container': '#21172c',
        'outline-variant': '#ccc4cc',
        tertiary: '#000000',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#151e12',
        'block-mint': '#C8E6CD',
        outline: '#7b757c',
        'on-secondary-container': '#5f6161',
        'accent-magenta': '#FF3D8B',
        'block-lime': '#DCEEB1',
        'on-primary-fixed': '#21172c',
        'surface-container-high': '#ece7e9',
        'surface-container-low': '#f8f2f4',
        'tertiary-container': '#151e12',
        'inverse-primary': '#d1c0dd',
        'block-coral': '#F3C9B6',
        'on-tertiary-container': '#7d8777',
        'on-primary-container': '#8d7e98',
        'inverse-surface': '#323032',
        'on-background': '#1d1b1d',
        'surface-container-highest': '#e6e1e3',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#eedcf9',
        'surface-container': '#f2ecef',
        'block-lilac': '#C5B0F4',
        'inverse-on-surface': '#f5eff1',
        'on-secondary-fixed-variant': '#454747',
        'on-primary': '#ffffff',
        midnight: '#04000D',
        'lime-bright': '#D6FF00',
        'off-white': '#F5F5F5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        'container-max': '1280px',
        'section-gap': '96px',
        sm: '16px',
        lg: '32px',
        xl: '48px',
        unit: '8px',
        md: '24px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Geist'],
        'headline-lg': ['Geist'],
        'display-lg': ['Geist'],
        'display-xl': ['Geist'],
        caption: ['JetBrains Mono'],
        'body-lg': ['Geist'],
        'body-md': ['Geist'],
        button: ['Geist'],
        eyebrow: ['JetBrains Mono'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-xl': ['86px', { lineHeight: '1.0', letterSpacing: '-0.02em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['18px', { lineHeight: '1.45', letterSpacing: '-0.01em', fontWeight: '400' }],
        button: ['18px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '500' }],
        eyebrow: ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      animation: {
        marquee: 'marquee 35s linear infinite',
        float: 'float 6s ease-in-out infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(5deg)' },
        },
      },
    },
  },
  plugins: [],
}